version: 2

before:
  hooks:
    - go mod tidy
    - sh -c "cd web && npm ci && npm run build"
    - sh -c "rm -rf cmd/blackwood/static && cp -r web/dist cmd/blackwood/static"

builds:
  - id: blackwood
    main: ./cmd/blackwood
    binary: blackwood
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: blackwood
    builds:
      - blackwood
    name_template: "blackwood_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - blackwood.example.yaml
      - extras/blackwood.service
  - id: blackwood-latest
    builds:
      - blackwood
    name_template: "blackwood_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - blackwood.example.yaml
      - extras/blackwood.service

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: csweichel
    name: blackwood
